name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo su - root << 'EOF'

            echo "===== CURRENT USER ====="
            whoami

            cd /var/www/nodeapp

            echo "===== CURRENT DIRECTORY ====="
            pwd

            echo "===== GIT PULL ====="
            git pull origin main

            echo "===== INSTALL PACKAGES ====="
            npm install

            echo "===== RESTART PM2 ====="
            pm2 restart app

            echo "===== SAVE PM2 ====="
            pm2 save

            echo "===== PM2 STATUS ====="
            pm2 list

            echo "===== DEPLOYMENT COMPLETED ====="

            EOF
