name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      INSTANCE_ID: i-0d4d7f9f4d3a77baa
      LAUNCH_TEMPLATE: my-temo2
      AUTO_SCALING_GROUP: my-auto

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS Login
        run: aws sts get-caller-identity

      - name: Deploy Latest Code
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/nodeapp

            git pull origin main

            npm install

            pm2 restart app

            pm2 save

      - name: Create AMI
        run: |
          IMAGE_ID=$(aws ec2 create-image \
            --instance-id $INSTANCE_ID \
            --name "nodeapp-${{ github.run_number }}" \
            --description "GitHub Actions Deployment" \
            --no-reboot \
            --query 'ImageId' \
            --output text)

          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: Wait For AMI
        run: |
          aws ec2 wait image-available \
            --image-ids $IMAGE_ID

      - name: Create Launch Template Version
        run: |
          aws ec2 create-launch-template-version \
            --launch-template-name $LAUNCH_TEMPLATE \
            --source-version '$Latest' \
            --version-description "GitHub-${{ github.run_number }}" \
            --launch-template-data "{\"ImageId\":\"$IMAGE_ID\"}"

      - name: Get Latest Launch Template Version
        run: |
          VERSION=$(aws ec2 describe-launch-templates \
            --launch-template-names $LAUNCH_TEMPLATE \
            --query 'LaunchTemplates[0].LatestVersionNumber' \
            --output text)

          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set Default Launch Template Version
        run: |
          aws ec2 modify-launch-template \
            --launch-template-name $LAUNCH_TEMPLATE \
            --default-version $VERSION

      - name: Update Auto Scaling Group
        run: |
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name $AUTO_SCALING_GROUP \
            --launch-template LaunchTemplateName=$LAUNCH_TEMPLATE,Version='$Default'

      - name: Start Instance Refresh
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name $AUTO_SCALING_GROUP
