name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:

          host: ${{ secrets.EC2_HOST }}

          username: ${{ secrets.EC2_USER }}

          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |

            cd /var/www/nodeapp

            echo "Pull Latest Code"

            git pull origin main

            echo "Installing Packages"

            npm install

            echo "Restart PM2"

            pm2 restart app

            pm2 save

            echo "Deployment Completed"
